-- MySQL Script generated by MySQL Workbench
-- Thu May 20 12:35:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL COMMENT 'Id do usuário',
  `name` VARCHAR(45) NOT NULL,
  `document` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cellphone` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_valid` TINYTEXT NOT NULL DEFAULT 0,
  `is_confirmed` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`document` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cellphone_UNIQUE` (`cellphone` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '			';


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `id` INT NOT NULL,
  `person_type_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `is_valid` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_person_type1_idx` (`person_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_person_type1`
    FOREIGN KEY (`person_type_id`)
    REFERENCES `mydb`.`person_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  `person_id` INT NULL,
  PRIMARY KEY (`user_id`, `role_id`, `person_id`),
  INDEX `fk_user_role_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_role_person1_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`individual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`individual` (
  `person_id` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  PRIMARY KEY (`person_id`),
  CONSTRAINT `fk_individual_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `person_id` INT NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`person_id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_company_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company_partner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company_partner` (
  `company_id` INT NOT NULL,
  `partner_id` INT NOT NULL,
  PRIMARY KEY (`company_id`, `partner_id`),
  INDEX `fk_company_has_person_company1_idx` (`company_id` ASC) VISIBLE,
  INDEX `fk_company_partner_individual1_idx` (`partner_id` ASC) VISIBLE,
  CONSTRAINT `fk_company_has_person_company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`company` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_company_partner_individual1`
    FOREIGN KEY (`partner_id`)
    REFERENCES `mydb`.`individual` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person_data_sent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person_data_sent` (
  `id` INT NOT NULL,
  `person_id` INT NOT NULL,
  `field_name` VARCHAR(45) NOT NULL,
  `old_value` VARCHAR(45) NULL,
  `new_value` VARCHAR(45) NULL,
  `user_id` INT NOT NULL COMMENT 'Usuário que validou o campo',
  `is_valid` TINYINT NULL,
  `notes` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_person_data_sent_person1_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_person_data_sent_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_person_data_sent_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_data_sent_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person_guarantor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person_guarantor` (
  `person_id` INT NOT NULL,
  `guarantor_id` INT NOT NULL,
  PRIMARY KEY (`person_id`, `guarantor_id`),
  INDEX `fk_person_guarantor_person_idx` (`person_id` ASC) INVISIBLE,
  CONSTRAINT `fk_person_guarantor_person1`
    FOREIGN KEY (`guarantor_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_guarantor_person2`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
